experiment_name: MAG assembly pipeline 

input: 
  sample table: inputs/illumina_samples.tsv
  seq data type: illumina short read  # alternative: nanopore long read
  adapter_file: inputs/all_illumina_adapters.fa  

database: 
  checkM database: /nfs/chisholmlab002/nvo/databases/checkM2_database/CheckM2_database/uniref100.KO.1.dmnd
  GTDB database: /nfs/chisholmlab002/nvo/databases/GTDB/release220

scratch directory: scratch
results directory: results